### ISSUE TITLE
extendedWaitUntil - Timeout can take a string ID, instead of an integer

### ISSUE THREAD

**Issue by simon-gilmurray** [Mastersam07/maestro-workbench#10]
<img width="611" alt="Screenshot 2025-01-02 at 17 35 55" src="https://github.com/user-attachments/assets/96db3e39-88f6-417a-8e0c-368d648aeae7" />

Sample code:
```
- extendedWaitUntil:
    visible:
      text: 'ENTER CODE'
    timeout: ${output.constants.LONGTIMEOUT}
```
