### ISSUE TITLE
addMedia command only supports the array form

### ISSUE THREAD

**Issue by Fishbowler** [Mastersam07/maestro-workbench#12]
Even though the [docs](https://maestro.mobile.dev/api-reference/commands/addmedia) don't show it, the [source](https://github.com/mobile-dev-inc/maestro/tree/main/maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlAddMedia.kt) shows that this is just version, and that a longer version is possible:

```
- addMedia:
    label: Try to add the test pictures to the device
    optional: true
    files:
      - test1.png
      - test2.png
```
