### ISSUE TITLE
Command 'evalScript' is missing

### ISSUE THREAD

**Issue by Fishbowler** [Mastersam07/maestro-workbench#22]
https://maestro.mobile.dev/api-reference/commands/evalscript

**Comment by Mastersam07** [comment]
A simple usage of evalScript is 

```yaml
- evalScript: ${output.myFlow = MY_NAME.toUpperCase()}
```

How is the label set, alongside optional?
```yaml
- evalScript:
    script: ${output.myFlow = MY_NAME.toUpperCase()}
    label: Some label
```
Like this?
