### ISSUE TITLE
Swipe from is currently not supporting index

### ISSUE THREAD

**Issue by simon-gilmurray** [Mastersam07/maestro-workbench#51]
<img width="634" alt="Image" src="https://github.com/user-attachments/assets/59431dd6-b571-4b46-82a7-e1bedec71735" />

```
- runFlow:
    when:
      platform: Android
    commands:
      - swipe:
          from:
            id: 'android:id/numberpicker_input'
            index: 2
          direction: DOWN
      - tapOn:
          id: 'android:id/button1'
          text: 'OK'
```
